name: schnorr-nizk
version: 0.1.0
synopsis: An implementation of the Schnorr protocol
description: An implementation of the Schnorr protocol
maintainer: Adjoint Inc (info@adjoint.io)
license: Apache
github: adjoint-io/schnorr-nizk
category: Cryptography

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/schnorr-nizk#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  schnorr-nizk-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - schnorr-nizk

tests:
  schnorr-nizk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - schnorr-nizk
